import { Market, Product, Vendor, Order, Job } from "@/types";

export const markets: Market[] = [
  {
    id: "1",
    name: "Makola Market",
    location: "Accra Central, Greater Accra",
    image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800",
    description: "Ghana's largest and most vibrant open-air market, offering everything from fresh produce to fabrics.",
    operatingHours: "6:00 AM - 6:00 PM",
    vendorCount: 450,
    rating: 4.7,
  },
  {
    id: "2",
    name: "Kaneshie Market",
    location: "Kaneshie, Accra",
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800",
    description: "A bustling market known for its fresh vegetables, fish, and household items.",
    operatingHours: "5:30 AM - 7:00 PM",
    vendorCount: 280,
    rating: 4.5,
  },
  {
    id: "3",
    name: "Kejetia Market",
    location: "Kumasi, Ashanti Region",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800",
    description: "West Africa's largest single-roof market with over 10,000 stores.",
    operatingHours: "6:00 AM - 8:00 PM",
    vendorCount: 890,
    rating: 4.8,
  },
  {
    id: "4",
    name: "Madina Market",
    location: "Madina, Accra",
    image: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800",
    description: "Popular local market with affordable prices and friendly vendors.",
    operatingHours: "6:00 AM - 6:30 PM",
    vendorCount: 320,
    rating: 4.3,
  },
];

export const vendors: Vendor[] = [
  {
    id: "v1",
    userId: "u1",
    marketId: "1",
    businessName: "Auntie Akua's Fresh Produce",
    description: "Fresh vegetables and fruits sourced daily from local farms.",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400",
    rating: 4.9,
    totalOrders: 1250,
    verified: true,
    categories: ["Vegetables", "Fruits"],
  },
  {
    id: "v2",
    userId: "u2",
    marketId: "1",
    businessName: "Nana Yaw Spices",
    description: "Premium local and imported spices for every dish.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400",
    rating: 4.7,
    totalOrders: 890,
    verified: true,
    categories: ["Spices", "Seasonings"],
  },
  {
    id: "v3",
    userId: "u3",
    marketId: "1",
    businessName: "Fresh Fish Corner",
    description: "Daily fresh fish from Tema Harbour.",
    image: "https://images.unsplash.com/photo-1510130113647-c4db5040b0cb?w=400",
    rating: 4.6,
    totalOrders: 670,
    verified: true,
    categories: ["Seafood", "Fish"],
  },
];

export const products: Product[] = [
  {
    id: "p1",
    vendorId: "v1",
    name: "Fresh Tomatoes",
    description: "Locally grown, perfectly ripe tomatoes",
    price: 15,
    unit: "kg",
    image: "https://images.unsplash.com/photo-1546470427-1d94d2abfc5b?w=400",
    category: "Vegetables",
    available: true,
    priceHistory: [
      { price: 12, date: new Date("2024-01-01") },
      { price: 14, date: new Date("2024-02-01") },
      { price: 15, date: new Date("2024-03-01") },
    ],
  },
  {
    id: "p2",
    vendorId: "v1",
    name: "Garden Eggs",
    description: "Fresh garden eggs, perfect for stews",
    price: 8,
    unit: "bunch",
    image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400",
    category: "Vegetables",
    available: true,
    priceHistory: [
      { price: 6, date: new Date("2024-01-01") },
      { price: 7, date: new Date("2024-02-01") },
      { price: 8, date: new Date("2024-03-01") },
    ],
  },
  {
    id: "p3",
    vendorId: "v1",
    name: "Kontomire (Cocoyam Leaves)",
    description: "Fresh green kontomire leaves",
    price: 5,
    unit: "bunch",
    image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400",
    category: "Vegetables",
    available: true,
    priceHistory: [
      { price: 4, date: new Date("2024-01-01") },
      { price: 5, date: new Date("2024-03-01") },
    ],
  },
  {
    id: "p4",
    vendorId: "v2",
    name: "Shito (Hot Pepper Sauce)",
    description: "Homemade authentic Ghanaian shito",
    price: 25,
    unit: "jar",
    image: "https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=400",
    category: "Spices",
    available: true,
    priceHistory: [
      { price: 22, date: new Date("2024-01-01") },
      { price: 25, date: new Date("2024-03-01") },
    ],
  },
  {
    id: "p5",
    vendorId: "v3",
    name: "Fresh Tilapia",
    description: "Fresh tilapia from Volta Lake",
    price: 45,
    unit: "kg",
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400",
    category: "Fish",
    available: true,
    priceHistory: [
      { price: 40, date: new Date("2024-01-01") },
      { price: 42, date: new Date("2024-02-01") },
      { price: 45, date: new Date("2024-03-01") },
    ],
  },
];

export const sampleOrders: Order[] = [
  {
    id: "o1",
    consumerId: "c1",
    marketId: "1",
    items: [
      {
        productId: "p1",
        productName: "Fresh Tomatoes",
        quantity: 2,
        unit: "kg",
        estimatedPrice: 30,
        vendorId: "v1",
        vendorName: "Auntie Akua's Fresh Produce",
      },
      {
        productId: "p4",
        productName: "Shito",
        quantity: 1,
        unit: "jar",
        estimatedPrice: 25,
        vendorId: "v2",
        vendorName: "Nana Yaw Spices",
      },
    ],
    status: "preparing",
    totalEstimate: 55,
    specialInstructions: "Please select firm tomatoes",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const availableJobs: Job[] = [
  {
    id: "j1",
    orderId: "o1",
    marketId: "1",
    itemCount: 5,
    vendorCount: 3,
    estimatedEarnings: 15,
    status: "available",
    consumerName: "Kofi A.",
  },
  {
    id: "j2",
    orderId: "o2",
    marketId: "1",
    itemCount: 8,
    vendorCount: 4,
    estimatedEarnings: 22,
    status: "available",
    consumerName: "Ama K.",
  },
  {
    id: "j3",
    orderId: "o3",
    marketId: "1",
    itemCount: 3,
    vendorCount: 2,
    estimatedEarnings: 10,
    status: "available",
    consumerName: "Kwame O.",
  },
];

export const categories = [
  { id: "1", name: "Vegetables", icon: "🥬", count: 45 },
  { id: "2", name: "Fruits", icon: "🍎", count: 32 },
  { id: "3", name: "Fish & Seafood", icon: "🐟", count: 28 },
  { id: "4", name: "Meat & Poultry", icon: "🍖", count: 24 },
  { id: "5", name: "Spices", icon: "🌶️", count: 56 },
  { id: "6", name: "Grains", icon: "🌾", count: 18 },
  { id: "7", name: "Oils", icon: "🫒", count: 12 },
  { id: "8", name: "Household", icon: "🧹", count: 67 },
];
